### ISSUE TITLE
Increase refresh rate on object detection

### ISSUE THREAD

**Issue by UEDEVLabs** [mbaske/yolo-unity#5]
Can we increase the refresh rate that objects detection it's detecting slower.nearly `900ms.
is there any system to increase detection speed.because of this it not detecting realtime?

@mbaske 
Thanks

**Comment by mbaske** [comment]
Hi @smartcharith, the classifier takes a moment to detect objects, but I think most of the lag is due to the signal roundtrip via GRPC. [ClientManager](https://github.com/mbaske/yolo-unity/blob/master/YoloUnity/Assets/Scripts/Yolo/Service/ClientManager.cs) logs both durations to the Unity console. I'm not sure how to decrease the lag, given the current setup. My initial attempt was to integrate the Yolo DLLs as Unity plugins, but I couldn't quite get that working. Here's an older project which apparently accomplished this https://github.com/tran-brian/yolo-unity-integration

**Comment by UEDEVLabs** [comment]
i just used this asset:
https://assetstore.unity.com/packages/tools/integration/opencv-for-unity-21088

it has YOLO integration for unity. but it not support to recognized game objects that inside unity editor.
it reads webcam feed only. 
i'm out of solutions!!

Please @mbaske

**Comment by DBrown12** [comment]
Do we know if the wrapper can work on depth camera reads for example using a RealSense D435 Camera?

**Comment by mbaske** [comment]
> Do we know if the wrapper can work on depth camera reads for example using a RealSense D435 Camera?

You mean the Alturos code? https://github.com/AlturosDestinations/Alturos.Yolo
I think you could feed it pretty much any visual information. But the question is if you have a matching classifier. You'd probably need to train your own YOLO model for making sense of depth camera reads.
